### ISSUE TITLE
jQuery compatibility would be nice as an option

### ISSUE THREAD

**Issue by bradlis7** [otaq/sortable-rails#1]
I'm not sure if you can include a second package that can be required in `application.js`, but adding the jQuery compatibility layer would be nice (`jquery.binding.js`).

**Comment by otaq** [comment]
@bradlis7 Sorry for the late reply, seems my email notification is off. I just turn it on.

it's kinda easy to add jQuery compatibility layer, you wanna make a pull request?

If not, let me know. I will do. It's completely OK, just a chance for you to contribute open source.

Thanks for mention me to do this.

**Comment by bradlis7** [comment]
Not too bad to add it in. Hopefully I linked it up correctly.
