### ISSUE TITLE
FileNotFound: couldn't find file 'sortable-rails'

### ISSUE THREAD

**Issue by maaroufious** [otaq/sortable-rails#3]
Hello,
I followed the instructions and added to `application.js`
```
//= require sortable-rails
//= require_tree .
``` 

But when trying to include application.js in my html files `javascript_include_tag("application")`, 
I am getting the following error:
`#<Sprockets::FileNotFound: couldn't find file 'sortable-rails'>
 `

**Comment by otaq** [comment]
@maaroufious Please provide your source code or any other information like rails version in order to reproduce the bug on my machine and help you to fix this problem. Thanks

**Comment by maaroufious** [comment]
@otaq Thanks for your reply. Everything is working now, the problem was in bundle. But I had to remove `//= require_tree .` for it to work. So my `application.js` looks like 
```
.
.
//= require sortable-rails
```
